####################################################
# hugs-pipe params
####################################################

data_dir: '/tigress/HSC/HSC/rerun/production-20160523'

band_detect: 'i'

band_verify: 'g'

band_meas: 'gr'  # band_detect always included

randoms_db_fn: ~

thresh_low:
    thresh: 3.0
    npix: 20
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev

thresh_high:
    thresh: 28.0
    npix: 1
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev

clean:
    max_frac_high_thresh: 0.15       # per footprint
    min_pix_low_thresh: 3 psf sigma  # per footprint
    name_high: 'THRESH_HIGH'
    n_sig_grow: 2.4

sextractor:
    config: 
        DETECT_THRESH: 0.7
        FILTER_NAME: '/home/jgreco/projects/hugs/hugs/sextractor/config/gauss_6.0_31x31.conv'
        BACK_SIZE: 128
        VERBOSE_TYPE: 'QUIET'
        DETECT_MINAREA: 100
        PHOT_APERTURES: '3,4,5,42,54'
        MAG_ZEROPOINT: 27.0
    params: [
        'X_IMAGE', 'Y_IMAGE', 'ALPHA_J2000', 'DELTA_J2000', 
        'MAG_AUTO', 'FLUX_RADIUS', 'A_IMAGE', 'B_IMAGE', 
        'THETA_IMAGE', 'ELLIPTICITY', 'KRON_RADIUS', 
        'FWHM_IMAGE', 'FLAGS', 'MAG_APER(1)', 'MAG_APER(2)',
        'MAG_APER(3)', 'MAG_APER(4)', 'MAG_APER(5)'
    ]
    delete_created_files: True
    sex_io_dir: '/scratch/network/jgreco/sextractor-io'
    verify_max_sep: 15  # pixels

####################################################################
# synthetic UDG parameters (only used if num_synths>0)
####################################################################
synth_pset_lims:
    n: [0.6, 1.2]
    mu_0(i): [23, 27]
    ell: [0.2, 0.2]
    r_e: [2, 7]
        ####ex_io_dir:###############################################################
