####################################################
# hugs-pipe params
####################################################

data_dir: '/scratch/gpfs/jiaxuanl/Data/SALAD/' 
hugs_io: '/scratch/gpfs/jiaxuanl/Data/SALAD/hugs-io'

mean_seeing_sigma: 1.5

pixel_scale: 0.262

zpt: 22.5

min_good_data_frac: 0.5

bright_star:
    bright_star_thresh: 13
    p1: 0.8
    p2: 0.8

band_detect: 'r'

band_mask: 'r'

band_verify: 'g'

band_meas: 'gr' # band_detect always included

thresh_type: SB  # SB or stddev

thresh_low:
    thresh: 24. #24.5 # mag/arcsec^2 
    npix: 20
    n_sig_grow: 15
    isogrow: False
    thresh_type: stdev

thresh_high:
    thresh: 21.75 #22.5 # mag/arcsec^2
    npix: 10
    n_sig_grow: 10
    thresh_type: stdev

clean:
    max_frac_high_thresh: 0.15  # per footprint
    name_high: 'THRESH_HIGH'
    n_sig_grow: 10.0
    min_pix_low_thresh: 3 psf sigma
    back_size: 160

small_sources_r_max: 6 #2.0
lsb_smooth_factor: 1.75 # lsb_smooth_factor * psf_sigma
max_smooth_sigma: 3.0

sep_steps:
    extract_pixstack: 600000
    sep_point_sources:
        min_radius: 6 #2.0 # pixel
        radius_colname: 'flux_radius'
        mask_grow: 3
        do_measure: True
        sep_extract_kws:
            thresh: 1.5
            minarea: 10
            deblend_cont: 0.001
            filter_num_fwhm: 1.0
        sep_back_kws:
            bw: 32
            bh: 32
            fw: 3
            fh: 3
            fthresh: 0.0

sextractor:
    config: 
        BACK_SIZE: 450
        PIXEL_SCALE: 0.262
        DETECT_THRESH: 2.5
        THRESH_TYPE: "RELATIVE"
        # FILTER_NAME: '/home/jiaxuanl/Research/Packages/sextractor-2.25.0/config/default.conv'
        FILTER_NAME: '/home/jiaxuanl/Research/Packages/sextractor-2.25.0/config/gauss_5.0_9x9.conv'
        # FILTER_NAME: '/home/jiaxuanl/Research/Packages/sextractor-2.25.0/config/gauss_6.0_31x31.conv'
        # FILTER_NAME: "/scratch/gpfs/jiaxuanl/Data/SALAD/sextractor-io/gauss_5.0_15x15.conv"
        FILTER: "Y"
        VERBOSE_TYPE: "QUIET"
        DETECT_MINAREA: 600
        MAG_ZEROPOINT: 22.5
        SEEING_FWHM: 0.7 # this is used for star/gal separation
        DEBLEND_NTHRESH: 8
        DEBLEND_MINCONT: 0.1
        MEMORY_PIXSTACK: 900000
        WEIGHT_TYPE: "BACKGROUND" # this is IMPORTANT!!
    delete_created_files: False
    sex_io_dir: '/scratch/gpfs/jiaxuanl/Data/SALAD/sextractor-io'
    verify_max_sep: 4 # We no longer use pixels for separation. Instead, we use `verify_max_sep` times r_eff for each object.

####################################################
# Synths
####################################################

inject_synths: False
