####################################################
# hugs-pipe params
####################################################

data_dir: '/tigress/HSC/DR/s18a_wide' 
hugs_io: '/scratch/gpfs/jgreco/hugs-io'
 
min_good_data_frac: 0.75

band_detect: 'g'

band_mask: 'i'

band_verify: 'r'

band_meas: 'ri'  # band_detect always included

thresh_type: SB  # SB or stddev

thresh_low:
    thresh: 24.5 # mag/arcsec^2 
    npix: 20
    n_sig_grow: 7.2
    isogrow: False
    thresh_type: stdev

thresh_high:
    thresh: 22. # mag/arcsec^2
    npix: 10
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev

clean:
    max_frac_high_thresh: 0.15  # per footprint
    name_high: 'THRESH_HIGH'
    n_sig_grow: 2.4
        
hsc_small_sources_r_max: 2.0

sep_steps:
    extract_pixstack: 600000
    sep_point_sources:
        min_radius: 2.0 # arcsec
        mask_grow: 3
        do_measure: True
        sep_extract_kws:
            thresh: 1.5
            minarea: 10
            deblend_cont: 0.001
            filter_num_fwhm: 1.0
        sep_back_kws:
            bw: 64
            bh: 64
            fw: 3
            fh: 3
            fthresh: 0.0

sextractor:
    config: 
        PIXEL_SCALE: 0.168
        DETECT_THRESH: 0.6
        THRESH_TYPE: RELATIVE
        FILTER_NAME: '/home/jgreco/projects/hugs/hugs/sextractor/config/gauss_6.0_31x31.conv'
        BACK_SIZE: 256
        VERBOSE_TYPE: 'QUIET'
        DETECT_MINAREA: 100
        MAG_ZEROPOINT: 27.0
        SEEING_FWHM: 0.7
        MEMORY_PIXSTACK: 900000
    delete_created_files: True
    sex_io_dir: '/scratch/gpfs/jgreco/sextractor-io'
    verify_max_sep: 15  # pixels

####################################################
# Synths
####################################################

inject_synths: False
