density: 360 # per square degree
min_sep: 50

ra_lim_list: [[27.8, 40.2],
              [15.3, 23],  
              [329, 344], 
              [344, 360], 
              [0, 4],
              [211, 251],
              [127, 143],
              [143, 155], 
              [147, 152], 
              [172, 194],
              [197, 202],
              [204, 227], 
              [212, 216]] 
  
dec_lim_list: [[-7.2, 0],
               [-1, 2.5],
               [-1.6, 7.5],
               [-1.6, 3],
               [-1.5, 3],
               [41.6, 45],
               [-2.6, 5.6], 
               [-2.6, 2.3], 
               [2.3, 4.5], 
               [-2.5, 2.2], 
               [-2.0, 1], 
               [-2.5, 2.2], 
               [51.7, 53.3]]
 
mu_range: [22.5, 29.0]
r_eff_range: [3, 25]
n_range: [0.8, 1.2]
theta_range: [0, 180]
ell_range: [0., 0.6]

master_band: 'g'
mu_type: average

#  med:
#  median g-i = 0.64
#  median g-r = 0.43
#
#  reds:
#  median g-i = 0.82
#  median g-r = 0.56
#
#  blues:
#  median g-i = 0.47
#  median g-r = 0.32
