density: 360 # per square degree
min_sep: 30

ra_lim_list: [[32, 40],
              [14, 23],  
              [330, 350], 
              [350, 360], 
              [0, 3],
              [199, 251],
              [128, 143],
              [143, 161], 
              [167, 226]] 
  
dec_lim_list: [[-7, 3],
               [-2, 3],
               [-2, 7],
               [-2, 3],
               [-2, 3],
               [42, 45],
               [-2, 5], 
               [-2, 2], 
               [-2, 2]]
 
mu_range: [22, 27.5]
r_eff_range: [3, 10]
n_range: [0.8, 1.2]
theta_range: [0, 180]
ell_range: [0., 0.6]

master_band: 'g'
mu_type: central

g_i: 0.47
g_r: 0.32
