density: 360 # per square degree
min_sep: 30

ra_lim_list: [[32, 40],
              [14, 23],  
              [330, 360], 
              [0, 4],
              [199, 251],
              [128, 226]] 
  
dec_lim_list: [[-7, 3],
               [-2, 3],
               [-2, 7],
               [-2, 3],
               [42, 45],
               [-2, 5]]
 
mu_range: [22, 27.5]
r_eff_range: [3, 10]
n_range: [0.8, 1.2]
theta_range: [0, 180]
ell_range: [0., 0.6]

master_band: 'g'
mu_type: central
