density: 360 # per square degree

ra_lim_list: [[28, 42], 
              [126, 143], 
              [175, 184], 
              [208, 228], 
              [234, 250], 
              [328, 346]]
  
dec_lim_list: [[-8, -1], 
               [-3, 6], 
               [-3, 2], 
               [-3, 3], 
               [41, 45], 
               [-2, 4]]
 
min_sep: 30

mu_range: [22, 27.5]
r_eff_range: [3, 10]
n_range: [0.8, 1.2]
theta_range: [0, 180]
ell_range: [0., 0.6]

mu_type: central
