density: 400 # per square degree

ra_lim_list: [[28, 42], 
              [126, 143], 
              [175, 184], 
              [208, 228], 
              [234, 250], 
              [328, 346]]
  
dec_lim_list: [[-8, -1], 
               [-3, 6], 
               [-3, 2], 
               [-3, 3], 
               [41, 45], 
               [-2, 4]]
 
min_sep: 30

mu_range: [24, 27]
r_eff_range: [4, 10]
n_range: [0.3, 1.2]
theta_range: [0, 180]

mu_type: average
