data_dir: hsc

thresh_low:
    thresh: 3.25
    npix: 50
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev

thresh_high:
    thresh: 20.0
    npix: 1
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev

assoc:
    r_in: 0
    r_out: 15
    min_pix: 8 psf sigma
    max_on_bit: 10
    dilate: ~

thresh_det:
    thresh: 3.25
    npix: 50
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev
    kern_fwhm: 3.5 # arcsec

deblend_stamps:
    npix: 5 
    kern_sig_pix: 2.5 psf sigma
    thresh_snr: 0.5
    detect_kwargs:
        sigclip_sigma: 3.0
        sigclip_iters: ~
    deblend_kwargs:
        nlevels: 32
        contrast: 0.001
        mode: exponential
        connectivity: 8

photometry:
    ell_nsig: 4.0
    circ_radii: [3, 6, 9]
