####################################################
# hugs-pipe params
####################################################

data_dir: hsc

band_detect: 'i'

band_verify: 'gr'

thresh_low:
    thresh: 3.0
    npix: 20
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev

thresh_high:
    thresh: 28.0
    npix: 1
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev

clean:
    max_frac_high_thresh: 0.15       # per footprint
    min_pix_low_thresh: 3 psf sigma  # per footprint
    name_high: 'THRESH_HIGH'
    n_sig_grow: 2.4

thresh_det:
    thresh: 3.25
    npix: 50
    n_sig_grow: 2.4
    isogrow: False
    thresh_type: stdev
    kern_fwhm: 6.0 # arcsec

find_blends:
    name_low: 'THRESH_LOW'
    num_low_fps: 2
    min_fp_area: 150
    min_parent_area: 0.15
    min_parent_flux: 0.6

sex_measure:
    config: 
        DETECT_THRESH: 0.7
        FILTER_NAME: 'gauss_7.0_31x31.conv'
        BACK_SIZE: 128
        VERBOSE_TYPE: 'NORMAL'
        DETECT_MINAREA: 100
    apertures: [3., 4., 5., 6., 7., 8., 16., 32.]

verify_max_sep: 15  # pixels

run_imfit:
    bbox_grow: 120
    psf_convolve: False
    clean: True
    save_fit_fig: False
